# Generated by Django 4.1.7 on 2023-04-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_registration_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='workers_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_face', models.BinaryField()),
                ('field', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('exp_cnf', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=100)),
                ('image_work', models.BinaryField()),
            ],
        ),
    ]
