# Generated by Django 4.1.7 on 2023-04-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_workers_data_image_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers_data',
            name='image_work',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
