# Generated by Django 4.1.7 on 2023-04-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_workers_data_image_face_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers_data',
            name='image_face',
            field=models.ImageField(default='0', upload_to=''),
        ),
    ]
