# Generated by Django 4.1.7 on 2023-04-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_workers_data_image_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers_data',
            name='image_face',
            field=models.FileField(default='0', upload_to=''),
        ),
    ]
