# Generated by Django 4.1.7 on 2023-04-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_workers_data_image_face_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_data',
            name='uid',
            field=models.IntegerField(default=0),
        ),
    ]
