# Generated by Django 4.1.7 on 2023-04-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_registration_data_uid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registration_create',
        ),
        migrations.RemoveField(
            model_name='registration_data',
            name='uid',
        ),
        migrations.AddField(
            model_name='registration_data',
            name='password',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='registration_data',
            name='uname',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
