# Generated by Django 4.1.7 on 2023-04-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_registration_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_data',
            name='uid',
            field=models.IntegerField(default=0),
        ),
    ]
