# Generated by Django 4.1.7 on 2023-04-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_registration_data_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_create',
            name='uid',
            field=models.IntegerField(default=0),
        ),
    ]
