# Generated by Django 4.1.7 on 2023-04-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_registration_create_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration_create',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='registration_data',
            name='uid',
        ),
        migrations.AlterField(
            model_name='registration_create',
            name='password',
            field=models.CharField(default='0', max_length=40),
        ),
        migrations.AlterField(
            model_name='registration_create',
            name='uname',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
