# Generated by Django 4.1.7 on 2023-05-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_registration_create_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_data',
            name='sex',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
