# Generated by Django 4.1.7 on 2023-05-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_registration_data_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers_data',
            name='image_work',
        ),
        migrations.AddField(
            model_name='workers_data',
            name='image_work1',
            field=models.ImageField(db_column='photo1', default='0', upload_to='images'),
        ),
        migrations.AddField(
            model_name='workers_data',
            name='image_work2',
            field=models.ImageField(db_column='photo2', default='0', upload_to='images'),
        ),
        migrations.AddField(
            model_name='workers_data',
            name='image_work3',
            field=models.ImageField(db_column='photo3', default='0', upload_to='images'),
        ),
    ]
