# Generated by Django 4.1.7 on 2023-05-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_workers_data_image_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_data',
            name='uid',
            field=models.IntegerField(default='0', max_length=40),
        ),
    ]
