# Generated by Django 4.1.7 on 2023-05-02 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_registration_data_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration_data',
            name='uid',
        ),
    ]
