# Generated by Django 4.1.7 on 2023-05-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_registration_data_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_data',
            name='role',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
