# Generated by Django 4.1.7 on 2023-05-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_workers_data_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers_data',
            name='name',
            field=models.CharField(default='0', max_length=40),
        ),
    ]
