# Generated by Django 4.1.7 on 2023-05-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_workers_data_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(default='0', max_length=100)),
                ('password', models.CharField(default='0', max_length=40)),
            ],
        ),
    ]
